// <auto-generated />
using System;
using Citas.Domain.Enums;
using Citas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Citas.Infrastructure.Migrations
{
    [DbContext(typeof(CitasDbContext))]
    partial class CitasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum__day", new[] { "friday", "monday", "saturday", "sunday", "thursday", "tuesday", "wednesday" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "enum__reservation_state", new[] { "cancelled", "completed", "confirmed", "pending" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Citas.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("first_name");

                    b.Property<bool>("HasAccount")
                        .HasColumnType("boolean")
                        .HasColumnName("has_account");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("char(103)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.Property<int>("company_id")
                        .HasColumnType("integer");

                    b.Property<int?>("employee_schedule_id")
                        .HasColumnType("integer");

                    b.Property<int?>("position_id")
                        .HasColumnType("integer");

                    b.Property<int>("rol_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("company_id")
                        .HasDatabaseName("fk__employee_company");

                    b.HasIndex("employee_schedule_id")
                        .HasDatabaseName("fk__employee_employee_schedule");

                    b.HasIndex("position_id")
                        .HasDatabaseName("fk__employee_position");

                    b.HasIndex("rol_id")
                        .HasDatabaseName("fk__employee_rol");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.EmployeeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("company_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("company_id")
                        .HasDatabaseName("fk__employee_schedule_company");

                    b.ToTable("employee_schedule", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.EmployeeScheduleException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<NpgsqlRange<DateTime>>("RangeTime")
                        .HasColumnType("tstzrange")
                        .HasColumnName("range_time");

                    b.Property<int>("employee_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("employee_id")
                        .HasDatabaseName("fk__employee_schedule_exception_employee");

                    b.ToTable("employee_schedule_exception", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.EmployeeScheduleRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<EDay>("Day")
                        .HasColumnType("enum__day")
                        .HasColumnName("day");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<int>("employee_schedule_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("employee_schedule_id")
                        .HasDatabaseName("fk__employee_schedule_range_employee_schedule");

                    b.ToTable("employee_schedule_range", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.EmployeeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Rating")
                        .HasColumnType("real")
                        .HasColumnName("rating");

                    b.Property<int>("employee_id")
                        .HasColumnType("integer");

                    b.Property<int>("service_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("employee_id")
                        .HasDatabaseName("fk__employee_service_employee");

                    b.HasIndex("service_id")
                        .HasDatabaseName("fk__employee_service_service");

                    b.ToTable("employee_service", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("position", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientComment")
                        .HasColumnType("text")
                        .HasColumnName("client_comment");

                    b.Property<string>("EmployeeComment")
                        .HasColumnType("text")
                        .HasColumnName("employee_comment");

                    b.Property<double>("Price")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("price");

                    b.Property<NpgsqlRange<DateTime>>("RangeTime")
                        .HasColumnType("tstzrange")
                        .HasColumnName("range_time");

                    b.Property<float?>("RatingFromClient")
                        .HasColumnType("real")
                        .HasColumnName("rating_from_client");

                    b.Property<float?>("RatingFromEmployee")
                        .HasColumnType("real")
                        .HasColumnName("rating_from_employee");

                    b.Property<EReservationState>("State")
                        .HasColumnType("enum__reservation_state")
                        .HasColumnName("state");

                    b.Property<int>("client_id")
                        .HasColumnType("integer");

                    b.Property<int>("employee_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("client_id")
                        .HasDatabaseName("fk__reservation_client");

                    b.HasIndex("employee_id")
                        .HasDatabaseName("fk__reservation_employee");

                    b.ToTable("reservation", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsUnavailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unavailable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<float>("SuggestedPrice")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("suggested_price");

                    b.Property<int>("company_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("company_id")
                        .HasDatabaseName("fk__service_company");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("Citas.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Citas.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Citas.Domain.Entities.EmployeeSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("employee_schedule_id");

                    b.HasOne("Citas.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("position_id");

                    b.HasOne("Citas.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Position");

                    b.Navigation("Rol");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Citas.Domain.Entities.EmployeeSchedule", b =>
                {
                    b.HasOne("Citas.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Citas.Domain.Entities.EmployeeScheduleException", b =>
                {
                    b.HasOne("Citas.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Citas.Domain.Entities.EmployeeScheduleRange", b =>
                {
                    b.HasOne("Citas.Domain.Entities.EmployeeSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("employee_schedule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Citas.Domain.Entities.EmployeeService", b =>
                {
                    b.HasOne("Citas.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Citas.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Citas.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Citas.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("client_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Citas.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Citas.Domain.Entities.Service", b =>
                {
                    b.HasOne("Citas.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("company_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
